### ISSUE TITLE
Add secrets.yaml.example to repo

### ISSUE THREAD

**Issue by jekader** [trip5/EspHome-VFD-Clock#1]
The build expects `secrets.yaml` to be present - include a `secrets.yaml.example` file with a note in the readme on how to fill it (also, add secrets.yaml to .gitignore)

**Comment by trip5** [comment]
Sorry didn't see this one earlier.  Yeah, this is standard when sharing YAML code online to use this format.  Unfortunately, the command line version of ESPHome doesn't make it clear where this file is supposed to reside, except when I used VSCode Studio, I had to put it in the same folder as the project... Like I said in the other answer, this is easily solved by using ESPHome's Docker version, which handles Secrets through the GUI.
